act0: false
act1: true
act2: false
act3: false
act4: true
dp0_0: 0.7
dp0_1: 0.7
dp1: 0.0
dp2: 0.1
dp3: 0.3
epoch: 4000
hidden_dim_1: 64
hidden_dim_2: 32
layer1: 2
layer2: 1
layer3: 1
ln0: true
ln1: false
ln2: false
ln3: true
ln4: true
lr: 0.001
