act0: false
act1: true
act2: false
act3: true
act4: true
dp0_0: 0.8
dp0_1: 0.5
dp1: 0.5
dp2: 0.0
dp3: 0.0
epoch: 4000
hidden_dim_1: 96
hidden_dim_2: 64
layer1: 3
layer2: 2
layer3: 1
ln0: true
ln1: true
ln2: true
ln3: false
ln4: true
lr: 0.0005
