act0: false
act1: true
act2: true
act3: false
act4: false
dp0_0: 0.8
dp0_1: 0.5
dp1: 0.3
dp2: 0.0
dp3: 0.2
epoch: 4000
hidden_dim_1: 32
hidden_dim_2: 24
layer1: 3
layer2: 2
layer3: 1
ln0: true
ln1: true
ln2: true
ln3: true
ln4: true
lr: 0.0005
