act0: false
act1: true
act2: false
act3: false
act4: true
dp0_0: 0.0
dp0_1: 0.0
dp1: 0.3
dp2: 0.0
dp3: 0.3
epoch: 4000
hidden_dim_1: 32
hidden_dim_2: 16
layer1: 3
layer2: 2
layer3: 2
ln0: true
ln1: false
ln2: false
ln3: false
ln4: true
lr: 0.01
