act0: false
act1: true
act2: true
act3: true
act4: true
dp0_0: 0.8
dp0_1: 0.5
dp1: 0.3
dp2: 0.0
dp3: 0.1
epoch: 4000
hidden_dim_1: 24
hidden_dim_2: 16
layer1: 3
layer2: 1
layer3: 2
ln0: true
ln1: true
ln2: false
ln3: true
ln4: true
lr: 0.001
