act0: false
act1: true
act2: false
act3: true
act4: false
dp0_0: 0.8
dp0_1: 0.5
dp1: 0.2
dp2: 0.4
dp3: 0.1
epoch: 4000
hidden_dim_1: 64
hidden_dim_2: 32
layer1: 2
layer2: 2
layer3: 1
ln0: true
ln1: true
ln2: false
ln3: true
ln4: true
lr: 0.005
