act0: false
act1: true
act2: false
act3: true
act4: true
dp0_0: 0.0
dp0_1: 0.0
dp1: 0.1
dp2: 0.1
dp3: 0.1
epoch: 4000
hidden_dim_1: 64
hidden_dim_2: 24
layer1: 3
layer2: 2
layer3: 1
ln0: true
ln1: true
ln2: true
ln3: true
ln4: true
lr: 0.001
