act_2wl0: true
act_2wl1: true
act_lin: false
alpha: 0.05
dp_2wl0: 0.1
dp_2wl1: 0.0
dp_lin0: 0.8
dp_lin1: 0.6
epoch: 200
gn_2wl1: false
hidden_dim_1wl: 256
hidden_dim_2wl: 16
layer1: 2
layer2: 2
layer3: 2
ln_2wl0: false
ln_2wl1: true
ln_lin: true
lr: 0.0005
reduce_feat: true
sum_pooling: true
use_appnp: true
use_degree: false
