act_1wl: false
act_2wl0: false
act_2wl1: true
dp_1wl: 0.0
dp_2wl0: 0.8
dp_2wl1: 0.8
epoch: 200
gn_1wl: false
gn_2wl1: false
hidden_dim_1wl: 128
hidden_dim_2wl: 32
layer1: 1
layer2: 2
layer3: 2
ln_1wl: true
ln_2wl0: true
ln_2wl1: false
lr: 0.001
use_degree: false
